use_frameworks!

platform :ios, '9.0'

target 'PJCrashProtector_Example' do
  pod 'PJCrashProtector', :path => '../'

  target 'PJCrashProtector_Tests' do
    inherit! :search_paths

#    pod 'Specta'
#    pod 'Expecta'
  end
end
